# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('materialmanager', '0002_auto_20170728_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='supplier',
        ),
    ]
