# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materialmanager', '0004_auto_20170728_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='processing',
            field=models.IntegerField(choices=[(0, '0%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')],
                                      default=25),
        ),
    ]
