# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materialmanager', '0005_auto_20170728_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='categories',
            field=models.ManyToManyField(to='materialmanager.Category'),
        ),
    ]
