# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import materialmanager.models


class Migration(migrations.Migration):
    dependencies = [
        ('materialmanager', '0008_auto_20170731_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=materialmanager.models.upload_location),
        ),
    ]
