# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 14:53
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms
import materialmanager.models


class Migration(migrations.Migration):
    dependencies = [
        ('materialmanager', '0009_auto_20170731_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, null=True,
                                                         upload_to=materialmanager.models.upload_location),
        ),
    ]
