# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 22:25
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms
import materialmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('materialmanager', '0010_auto_20170731_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='photo',
            field=django_resized.forms.ResizedImageField(upload_to=materialmanager.models.upload_location),
        ),
    ]
