# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-19 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialmanager', '0022_auto_20171019_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='notes',
            new_name='note',
        ),
    ]
